#!/bin/bash

ln -sf ~/Dropbox/backup/dotfiles/         ~/dotfiles

ln -sf ~/dotfiles/conkyrc                 ~/.conkyrc
ln -sf ~/dotfiles/tmux/tmux.conf          ~/.tmux.conf
ln -sf ~/dotfiles/vim/vimrc               ~/.vimrc
ln -sf ~/dotfiles/xinitrc                 ~/.xinitrc
ln -sf ~/dotfiles/zsh/zshrc               ~/.zshrc
ln -sf ~/dotfiles/vimperator              ~/.vimperator
ln -sf ~/dotfiles/awesome                 ~/.config/awesome
ln -sf ~/dotfiles/ctags                   ~/.ctags
